name: ocr_translate
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  translator: ^0.1.5
  flutter_mobile_vision: ^0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true